#  Probabilistic Performance Profiles 
# ------------------------------------
# This file contains a routine to plot the probabilistic performance profiles
# (PPP) generated by a benchmark experiment. The detailed description of PPPs
# can be found in:
#
# Barreto, A. M. S., Bernardino, H. S., and Barbosa, H. J. 2010. 
#   Probabilistic performance profiles for the experimental evaluation of
#   stochastic algorithms. 
#   In Proceedings of the 12th Annual Conference on Genetic and Evolutionary 
#   Computation (GECCO), pp. 751-758, ACM
#   DOI= http://doi.acm.org/10.1145/1830483.1830617 
#
# The program is written in R (see www.r-project.org). To use it, simply type
# > source("ppp.R")
# in the R environment prompt (without the ">"). The routine "ppp()" only
# requires two matrices: one containing the costs of the algorithms on each
# problem and the other containing the corresponding standard deviations. The
# complete documentation of the routine can be found below. Also, there is a
# simple function called "ppp.demo()" which demonstrates how to use the
# routine. To see it in action, type "ppp.demo()" within the R environment.
#
# ------------------------------------
# This program was written by Andre' da Motta Salles Barreto (amsb@lncc.br).
# You can freely modify it, but please keep the original reference.


ppp <- function(C, S = matrix(0, nrow(C),ncol(C)), 
			    min.tau = 0, max.tau = max(C[C!=Inf])+2*max(S), res = 1000, 
             print.legend = TRUE, leg = NULL, leg.pos = "bottomright",
             lwd = 2, ...) {

# C = matrix in which c_ij is the cost of algorithm j on problem i
#     (that is, each row corresponds to a problem and columns refer to
#     algorithms). Infinite costs are acceptable.
# S = matrix with standard deviations. By default s_ij = 0, ie, the
#     standard performance profiles are plotted
# min.tau = the lower limit of the x axis (default = 0)
# max.tau = the upper limit of the x axis (default = max cost + 2 sd)
# res = resolution of the plots;larger numbers generate smoother curves (slower)
# print.legend = should a legend be plotted?
# leg = legend in the format c("algorithm_1", "algorithm_2", ...); by default 
#       the legend c("rho_1", "rho_2", ...) is plotted
# leg.pos = position of the legend (see the documentation for function legend())
# lwd = line widths (default = 2)
# ... = extra graphical parameters can be passed on to the matplot() function
	mins <- apply(C,1,min)
   mins[mins == Inf] <- 1
 	C <- C / mins
	S <- S / mins

	x <- seq(min.tau, max.tau, length=res)
	
	PP <- matrix(0, length(x), ncol(C))
	
	for (i in 1:length(x)) {
		for (j in 1:ncol(C)) {
			for (k in 1:nrow(C)) {
               if (C[k,j] != Inf) {
                    PP[i,j] <- PP[i,j] + pnorm(x[i],C[k,j], S[k,j])
                    }
				}
			PP[i,j] <- PP[i,j] / nrow(C)
			}
		}   

	matplot(x, PP, t="l", lwd = lwd, xlab = expression(tau), ylab = "", ...)

   if (print.legend) {
      if (is.null(leg)) {
          leg <- expression()
          for(i in 1:ncol(C)) {
               leg <- c(leg, substitute(expression(bar(rho)[ind](x)),
                    list(ind=i))[[2]]) 
               }
          }
      legend(leg.pos, leg, lwd=lwd, col=1:ncol(C), lty=1:ncol(C), bg="WHITE")
      }
	}


ppp.demo <- function() {
#    Simplest use possible 
     C <- matrix(c(1,1,1,5,3,Inf,5.5,5.5,1,1,2,4,4,6.5,8),5,3)
     ppp(C)

     print("Press enter")
     readline()

#    Adding standard deviations to the curves
     S <- matrix(c(0.3,0.9,0.3,0.4,1,0.1,0.5,0.4,0.4,0.2,0.3,0.2,1,0.6,0.8),5,3)
     ppp(C,S)

     print("Press enter")
     readline()

#    Altering the legend
     leg <- c("Alg 1", "Alg 2", "Alg 3")
     ppp(C,S, leg = leg, leg.pos="topleft")

     }


print("ppp.R loaded")